### ISSUE TITLE
Some RBs are shown as dates in Chromium browsers

### ISSUE THREAD

**Issue by WonkySpecs** [WHTaylor/icat-admin#16]
The js Date API is browser dependent, and in some browsers it's parsing some RBs as dates. Do something better than https://github.com/WHTaylor/icat-admin/blob/c42b5b8460657bd52fa53f173a05d4dcd8a3a307/src/utils.js#L70

**Comment by WHTaylor** [comment]
Closed by [aea6b64](https://github.com/WHTaylor/icat-admin/pull/17/commits/aea6b64227772b8d88beb3be14241f747be0aa2a)
